# Meta Data for SEO

## Homepage
title = "Gilani's Notes"
titleSeparator = "-"
titleAddition = "Amin Gilani"
description = "As I continue through the Georgia Tech OMSCS program, I'll keep publishing my notes here."

## Open Graph + Twitter Cards
images = ["torch.png"]
twitterSite = "amingilani"
twitterCreator = "amingilani"
facebookAuthor = "itsamingilani"
facebookPublisher = "itsamingilani"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = "https://twitter.com/amingilani"
schemaLinkedIn = "https://www.linkedin.com/in/amingilani/"
schemaGitHub = "https://github.com/amingilani"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/amingilani/omscs-notes"
editPage = true
